### ISSUE TITLE
logging of matches and characters with matches

### ISSUE THREAD

**Issue by emjfyi** [MadnessLabs/MadnessCup#10]

**Comment by bwhitingdesigns** [comment]
Maybe we can place in a ratio system for the users. Showing their top three used characters.

**Comment by emjfyi** [comment]
Issue moved to [MadnessLabs/MadnessCup_Planning #16](https://github.com/MadnessLabs/MadnessCup_Planning/issues/16) via [**ZenHub**](https://www.zenhub.com/)
